name: Publish Docker image
on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  push_to_registry:
    if: github.repository == 'pekrau/dbshare'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: scilifelabdatacentre/dbshare:${{ steps.docker-tag.outputs.tag }}
