name: Publish Docker image
on:
  push:
    branches:
      - master
  release:
    types: [published]
jobs:
  push_to_registry:
    if: github.repository == 'pekrau/dbshare'
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Github Container Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DBSHARE_GITHUB_USERNAME }}
          password: ${{ secrets.DBSHARE_GITHUB_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/scilifelabdatacentre/dbshare
            ghcr.io/pekrau/dbshare
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
